"""Visualize separation replay frame NPZ with Open3D or Matplotlib."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Tuple

import numpy as np


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Visualize static/dynamic point clouds from one frame generated by "
            "scripts/run_separation_replay.py."
        )
    )

    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument(
        "--frame_npz",
        type=str,
        default=None,
        help="Direct path to one frame NPZ (e.g., frame_000000.npz).",
    )
    source_group.add_argument(
        "--frames_dir",
        type=str,
        default=None,
        help="Directory containing frame_*.npz files.",
    )

    parser.add_argument(
        "--frame_index",
        type=int,
        default=0,
        help="Frame index used with --frames_dir.",
    )
    parser.add_argument(
        "--backend",
        type=str,
        choices=["auto", "open3d", "matplotlib"],
        default="auto",
        help="Visualization backend.",
    )
    parser.add_argument(
        "--max_points",
        type=int,
        default=50000,
        help="Randomly subsample each class to at most this many points.",
    )
    parser.add_argument("--seed", type=int, default=0, help="Random seed for subsampling.")

    # Matplotlib-specific options
    parser.add_argument(
        "--point_size",
        type=float,
        default=1.0,
        help="Scatter point size for matplotlib backend.",
    )
    parser.add_argument(
        "--save_png",
        type=str,
        default=None,
        help="Optional output image path for matplotlib backend.",
    )
    parser.add_argument(
        "--no_show",
        action="store_true",
        help="Do not open an interactive window (useful for headless servers).",
    )

    return parser.parse_args()


def _resolve_frame_path(args: argparse.Namespace) -> Path:
    if args.frame_npz is not None:
        frame_path = Path(args.frame_npz)
        if not frame_path.is_file():
            raise FileNotFoundError(f"Frame file not found: {frame_path}")
        return frame_path

    frames_dir = Path(args.frames_dir)
    if not frames_dir.is_dir():
        raise FileNotFoundError(f"frames_dir not found: {frames_dir}")

    frame_files = sorted(frames_dir.glob("frame_*.npz"))
    if not frame_files:
        raise FileNotFoundError(f"No frame_*.npz found under: {frames_dir}")

    if args.frame_index < 0 or args.frame_index >= len(frame_files):
        raise IndexError(
            f"frame_index out of range: {args.frame_index}. "
            f"Available frames: 0..{len(frame_files)-1}."
        )

    return frame_files[args.frame_index]


def _load_frame(frame_path: Path) -> Tuple[np.ndarray, np.ndarray, float]:
    with np.load(str(frame_path), allow_pickle=False) as payload:
        static_points = np.asarray(payload["static_points_world"], dtype=np.float32)
        dynamic_points = np.asarray(payload["dynamic_points_world"], dtype=np.float32)

        if static_points.ndim != 2 or static_points.shape[1] != 3:
            raise ValueError(
                f"static_points_world must have shape (N,3), got {static_points.shape}."
            )
        if dynamic_points.ndim != 2 or dynamic_points.shape[1] != 3:
            raise ValueError(
                f"dynamic_points_world must have shape (N,3), got {dynamic_points.shape}."
            )

        timestamp_raw = payload.get("timestamp")
        if timestamp_raw is None:
            timestamp = float("nan")
        else:
            timestamp = float(np.asarray(timestamp_raw).reshape(-1)[0])

    return static_points, dynamic_points, timestamp


def _subsample(points: np.ndarray, max_points: int, rng: np.random.Generator) -> np.ndarray:
    if max_points <= 0 or points.shape[0] <= max_points:
        return points
    keep = rng.choice(points.shape[0], size=max_points, replace=False)
    return points[keep]


def _visualize_open3d(static_points: np.ndarray, dynamic_points: np.ndarray, title: str) -> None:
    try:
        import open3d as o3d
    except ImportError as exc:
        raise ImportError(
            "open3d is not installed. Install it with: pip install open3d"
        ) from exc

    geometries = []

    if static_points.shape[0] > 0:
        static_pcd = o3d.geometry.PointCloud()
        static_pcd.points = o3d.utility.Vector3dVector(static_points)
        static_color = np.tile(np.array([[0.65, 0.65, 0.65]], dtype=np.float64), (static_points.shape[0], 1))
        static_pcd.colors = o3d.utility.Vector3dVector(static_color)
        geometries.append(static_pcd)

    if dynamic_points.shape[0] > 0:
        dynamic_pcd = o3d.geometry.PointCloud()
        dynamic_pcd.points = o3d.utility.Vector3dVector(dynamic_points)
        dynamic_color = np.tile(np.array([[1.0, 0.2, 0.2]], dtype=np.float64), (dynamic_points.shape[0], 1))
        dynamic_pcd.colors = o3d.utility.Vector3dVector(dynamic_color)
        geometries.append(dynamic_pcd)

    geometries.append(o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5))

    o3d.visualization.draw_geometries(geometries, window_name=title)


def _visualize_matplotlib(
    static_points: np.ndarray,
    dynamic_points: np.ndarray,
    title: str,
    point_size: float,
    save_png: str | None,
    no_show: bool,
) -> None:
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise ImportError(
            "matplotlib is not installed. Install it with: pip install matplotlib"
        ) from exc

    fig = plt.figure(figsize=(8, 6))
    ax = fig.add_subplot(111, projection="3d")

    if static_points.shape[0] > 0:
        ax.scatter(
            static_points[:, 0],
            static_points[:, 1],
            static_points[:, 2],
            s=point_size,
            c="#A6A6A6",
            alpha=0.6,
            label="static",
        )

    if dynamic_points.shape[0] > 0:
        ax.scatter(
            dynamic_points[:, 0],
            dynamic_points[:, 1],
            dynamic_points[:, 2],
            s=point_size,
            c="#E53935",
            alpha=0.9,
            label="dynamic",
        )

    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.set_title(title)
    ax.legend(loc="upper right")

    if save_png is not None:
        save_path = Path(save_png)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(save_path), dpi=200, bbox_inches="tight")
        print(f"Saved figure to: {save_path}")

    if not no_show:
        plt.show()
    else:
        plt.close(fig)


def main() -> None:
    args = _parse_args()
    rng = np.random.default_rng(args.seed)

    frame_path = _resolve_frame_path(args)
    static_points, dynamic_points, timestamp = _load_frame(frame_path)

    static_points = _subsample(static_points, args.max_points, rng)
    dynamic_points = _subsample(dynamic_points, args.max_points, rng)

    title = (
        f"{frame_path.name} | timestamp={timestamp:.3f} | "
        f"static={static_points.shape[0]} dynamic={dynamic_points.shape[0]}"
    )
    print(f"Visualizing: {frame_path}")
    print(
        f"- static points: {static_points.shape[0]}"
        f" | dynamic points: {dynamic_points.shape[0]}"
    )

    backend = args.backend
    if backend == "auto":
        try:
            _visualize_open3d(static_points, dynamic_points, title)
            return
        except ImportError:
            backend = "matplotlib"

    if backend == "open3d":
        _visualize_open3d(static_points, dynamic_points, title)
    else:
        _visualize_matplotlib(
            static_points=static_points,
            dynamic_points=dynamic_points,
            title=title,
            point_size=args.point_size,
            save_png=args.save_png,
            no_show=args.no_show,
        )


if __name__ == "__main__":
    main()
